# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: mvn verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        java: [17]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: zulu
    - name: Cache local maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ matrix.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ matrix.os }}-m2
    - name: Build with Maven
      run: mvn -B -V -e "-Dstyle.color=always" verify -DskipFormat -DverifyFormat
      env:
        MAVEN_OPTS: -Djansi.force=true
    - name: View IT build log on failure
      if: ${{ failure() }}
      run: cat target/it/plugin-test/build.log

